# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [22]:
d1=['k1']
d2=['k1']['k2']
d3=['k1'][0]['k2'][1][0] 
d4=['k1'][2]['k2'][1]['k4'][2][0]


TypeError: ignored

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [16]:
import numpy as np
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
import numpy as np
array=np.arange(30,71,2)
print("Array of all the even integers from 30 to 70")
print(array)

Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


## 5. Create an array of all the even integers from 20 to 35

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a, b), axis=0)

array([1, 2, 3, 4, 5, 6])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
import pandas as pd
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [10]:
import datetime
import pandas as pd
test_date = datetime.datetime.strptime("01-01-2023", "%d-%m-%Y")
K = 41
date_generated = pd.date_range(test_date, periods=K)
print(date_generated.strftime("%d-%m-%Y"))

Index(['01-01-2023', '02-01-2023', '03-01-2023', '04-01-2023', '05-01-2023',
       '06-01-2023', '07-01-2023', '08-01-2023', '09-01-2023', '10-01-2023',
       '11-01-2023', '12-01-2023', '13-01-2023', '14-01-2023', '15-01-2023',
       '16-01-2023', '17-01-2023', '18-01-2023', '19-01-2023', '20-01-2023',
       '21-01-2023', '22-01-2023', '23-01-2023', '24-01-2023', '25-01-2023',
       '26-01-2023', '27-01-2023', '28-01-2023', '29-01-2023', '30-01-2023',
       '31-01-2023', '01-02-2023', '02-02-2023', '03-02-2023', '04-02-2023',
       '05-02-2023', '06-02-2023', '07-02-2023', '08-02-2023', '09-02-2023',
       '10-02-2023'],
      dtype='object')


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [15]:
import pandas as pd
data={'Name':['Raga Varshini R','Sabari Vasan R T','Tamilselvi Kumaresan'],'Age':['20','18','52']}
a=pd.DataFrame(data)
print(a)

                   Name Age
0       Raga Varshini R  20
1      Sabari Vasan R T  18
2  Tamilselvi Kumaresan  52


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [14]:
import datetime
import pandas as pd
test = datetime.datetime.strptime("01/01/2023","%d/%m/%Y")
k=41
dg = pd.date_range(test,periods=k)
print(dg.strftime("%d/%m/%Y"))

Index(['01/01/2023', '02/01/2023', '03/01/2023', '04/01/2023', '05/01/2023',
       '06/01/2023', '07/01/2023', '08/01/2023', '09/01/2023', '10/01/2023',
       '11/01/2023', '12/01/2023', '13/01/2023', '14/01/2023', '15/01/2023',
       '16/01/2023', '17/01/2023', '18/01/2023', '19/01/2023', '20/01/2023',
       '21/01/2023', '22/01/2023', '23/01/2023', '24/01/2023', '25/01/2023',
       '26/01/2023', '27/01/2023', '28/01/2023', '29/01/2023', '30/01/2023',
       '31/01/2023', '01/02/2023', '02/02/2023', '03/02/2023', '04/02/2023',
       '05/02/2023', '06/02/2023', '07/02/2023', '08/02/2023', '09/02/2023',
       '10/02/2023'],
      dtype='object')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [13]:
import pandas as pd
lists = [[1, 'aaa', 22],[2,'bbb', 25],[3,'ccc', 24]]
a = pd.DataFrame(lists,columns=['No','Letter','Numbers'])
print(a)

   No Letter  Numbers
0   1    aaa       22
1   2    bbb       25
2   3    ccc       24
